version: "3"

services:

  student-frontend:
    image: frontend-student
    container_name: student-frontend
    build: 
      context: ./frontend
    networks:
      - student-frontend-net
      - student-backend-net
    ports:
      - 4201:4200
    depends_on: 
      - student-backend

  student-backend:
    image: backend-student
    container_name: student-backend
    build: 
      context: ./backend
    networks:
      - student-backend-net
    ports:
      - 8081:8080
    depends_on: 
      - student-db

  student-db:
    image: db-student
    container_name: student-db
    build: 
      context: ./postgres
    networks:
      - student-backend-net
    ports:
      - 5433:5432
    environment:
      - DB_ENVIRONMENT_VARIABLE=any_value

networks:
  student-backend-net:
  student-frontend-net:
